from pydantic import BaseModel, Field
from typing import Optional, Literal


class EmailState(BaseModel):
    # Input
    email_content: str = Field(
        ..., description="Raw email text to be triaged"
    )

    # Triage outputs
    triage_decision: Optional[
        Literal["ignore", "notify_human", "respond"]
    ] = Field(
        default=None,
        description="Decision made by triage node"
    )

    triage_reason: Optional[str] = Field(
        default=None,
        description="Short explanation for triage decision"
    )

    triage_confidence: Optional[float] = Field(
        default=None,
        description="Model confidence in triage decision (0-1)"
    )

    # ReAct / reasoning layer (Milestone 1 basic)
    agent_thoughts: Optional[str] = Field(
        default=None,
        description="Free-form reasoning / plan produced by the agent."
    )

    draft_reply: Optional[str] = Field(
        default=None,
        description="Draft email reply generated by the agent when triage_decision='respond'."
    )
